### ISSUE TITLE
Make repo compatible with `go get` and  `go generate`

### ISSUE THREAD

**Issue by carlmjohnson** [cooperhewitt/go-ucd#6]
Is there a plan to make the repo work with `go get` and `go generate`? Right now, the repo assumes that it will be installed as the root of `$GOPATH`, which makes it incompatible with `go get`, and it uses a Makefile, which is fine, but it would be nice to use [go generate](http://blog.golang.org/generate), so that no non-Go tooling is needed to compile/install things.

**Comment by straup** [comment]
There isn't a specific plan, no but I can take a look. The whole path dependency thing and folder layout for stuff like `go get` struck me as a bit of a moving target at the time this was written but maybe things have settled down?

I would happy to have a simpler way of building things. I'll try to take a look shortly.

**Comment by carlmjohnson** [comment]
There's a lot of debate in the Go community about the future of versioning/packaging, but I think they've worked out the basic structure with the upcoming Go 1.5. The core ideas, however, are pretty much the same going back to Go 1.0 or so. If you read https://golang.org/doc/code.html it explains how you should layout your folders to work with the go tool.

In this case you should assume a structure like

GOPATH ← Wherever you want to put things on your local machine

GOPATH/src/github.com/cooperhewit/go-ucd ← Where this repo's source should live

GOPATH/bin ← where ucd will be installed by `go get github.com/cooperhewit/go-ucd`

**Comment by micahwalter** [comment]
@carlmjohnson can you elaborate a bit more? I'd like to organize this the way you've described, but just not sure where things "should" go... what else beyond the folder structure do I need to worry about?

**Comment by straup** [comment]
I have a better idea having done this a bunch recently. I'll submit a pull request, shortly.

**Comment by carlmjohnson** [comment]
Thanks @straup. I would submit a PR myself, but I don't have time to go through and clean things up.
